/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as VaultRouteImport } from './routes/vault'
import { Route as TransparencyRouteImport } from './routes/transparency'
import { Route as SosRouteImport } from './routes/sos'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SafeCorridorRouteImport } from './routes/safe-corridor'
import { Route as RecoverVaultRouteImport } from './routes/recover-vault'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as OrgRouteImport } from './routes/org'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as NetworkRouteImport } from './routes/network'
import { Route as MapRouteImport } from './routes/map'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LegalToolsRouteImport } from './routes/legal-tools'
import { Route as LawyerFinderRouteImport } from './routes/lawyer-finder'
import { Route as KnowYourRightsRouteImport } from './routes/know-your-rights'
import { Route as InternationalRouteImport } from './routes/international'
import { Route as ForensicsRouteImport } from './routes/forensics'
import { Route as FeedbackRouteImport } from './routes/feedback'
import { Route as DonateRouteImport } from './routes/donate'
import { Route as CurriculumRouteImport } from './routes/curriculum'
import { Route as CommunityRouteImport } from './routes/community'
import { Route as CheckInRouteImport } from './routes/check-in'
import { Route as CameraRouteImport } from './routes/camera'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AppStoreAssetsRouteImport } from './routes/app-store-assets'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchStreamIdRouteImport } from './routes/watch.$streamId'
import { Route as LegalTermsRouteImport } from './routes/legal.terms'
import { Route as LegalPrivacyRouteImport } from './routes/legal.privacy'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const VaultRoute = VaultRouteImport.update({
  id: '/vault',
  path: '/vault',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparencyRoute = TransparencyRouteImport.update({
  id: '/transparency',
  path: '/transparency',
  getParentRoute: () => rootRouteImport,
} as any)
const SosRoute = SosRouteImport.update({
  id: '/sos',
  path: '/sos',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeCorridorRoute = SafeCorridorRouteImport.update({
  id: '/safe-corridor',
  path: '/safe-corridor',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverVaultRoute = RecoverVaultRouteImport.update({
  id: '/recover-vault',
  path: '/recover-vault',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgRoute = OrgRouteImport.update({
  id: '/org',
  path: '/org',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const NetworkRoute = NetworkRouteImport.update({
  id: '/network',
  path: '/network',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalToolsRoute = LegalToolsRouteImport.update({
  id: '/legal-tools',
  path: '/legal-tools',
  getParentRoute: () => rootRouteImport,
} as any)
const LawyerFinderRoute = LawyerFinderRouteImport.update({
  id: '/lawyer-finder',
  path: '/lawyer-finder',
  getParentRoute: () => rootRouteImport,
} as any)
const KnowYourRightsRoute = KnowYourRightsRouteImport.update({
  id: '/know-your-rights',
  path: '/know-your-rights',
  getParentRoute: () => rootRouteImport,
} as any)
const InternationalRoute = InternationalRouteImport.update({
  id: '/international',
  path: '/international',
  getParentRoute: () => rootRouteImport,
} as any)
const ForensicsRoute = ForensicsRouteImport.update({
  id: '/forensics',
  path: '/forensics',
  getParentRoute: () => rootRouteImport,
} as any)
const FeedbackRoute = FeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => rootRouteImport,
} as any)
const DonateRoute = DonateRouteImport.update({
  id: '/donate',
  path: '/donate',
  getParentRoute: () => rootRouteImport,
} as any)
const CurriculumRoute = CurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => rootRouteImport,
} as any)
const CommunityRoute = CommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckInRoute = CheckInRouteImport.update({
  id: '/check-in',
  path: '/check-in',
  getParentRoute: () => rootRouteImport,
} as any)
const CameraRoute = CameraRouteImport.update({
  id: '/camera',
  path: '/camera',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AppStoreAssetsRoute = AppStoreAssetsRouteImport.update({
  id: '/app-store-assets',
  path: '/app-store-assets',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchStreamIdRoute = WatchStreamIdRouteImport.update({
  id: '/watch/$streamId',
  path: '/watch/$streamId',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/app-store-assets': typeof AppStoreAssetsRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/curriculum': typeof CurriculumRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/forensics': typeof ForensicsRoute
  '/international': typeof InternationalRoute
  '/know-your-rights': typeof KnowYourRightsRoute
  '/lawyer-finder': typeof LawyerFinderRoute
  '/legal-tools': typeof LegalToolsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/network': typeof NetworkRoute
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/privacy': typeof PrivacyRoute
  '/recover-vault': typeof RecoverVaultRoute
  '/safe-corridor': typeof SafeCorridorRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/transparency': typeof TransparencyRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/watch/$streamId': typeof WatchStreamIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/app-store-assets': typeof AppStoreAssetsRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/curriculum': typeof CurriculumRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/forensics': typeof ForensicsRoute
  '/international': typeof InternationalRoute
  '/know-your-rights': typeof KnowYourRightsRoute
  '/lawyer-finder': typeof LawyerFinderRoute
  '/legal-tools': typeof LegalToolsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/network': typeof NetworkRoute
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/privacy': typeof PrivacyRoute
  '/recover-vault': typeof RecoverVaultRoute
  '/safe-corridor': typeof SafeCorridorRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/transparency': typeof TransparencyRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/watch/$streamId': typeof WatchStreamIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/app-store-assets': typeof AppStoreAssetsRoute
  '/auth': typeof AuthRoute
  '/camera': typeof CameraRoute
  '/check-in': typeof CheckInRoute
  '/community': typeof CommunityRoute
  '/curriculum': typeof CurriculumRoute
  '/donate': typeof DonateRoute
  '/feedback': typeof FeedbackRoute
  '/forensics': typeof ForensicsRoute
  '/international': typeof InternationalRoute
  '/know-your-rights': typeof KnowYourRightsRoute
  '/lawyer-finder': typeof LawyerFinderRoute
  '/legal-tools': typeof LegalToolsRoute
  '/login': typeof LoginRoute
  '/map': typeof MapRoute
  '/network': typeof NetworkRoute
  '/onboarding': typeof OnboardingRoute
  '/org': typeof OrgRoute
  '/privacy': typeof PrivacyRoute
  '/recover-vault': typeof RecoverVaultRoute
  '/safe-corridor': typeof SafeCorridorRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/sos': typeof SosRoute
  '/transparency': typeof TransparencyRoute
  '/vault': typeof VaultRoute
  '/verify': typeof VerifyRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/terms': typeof LegalTermsRoute
  '/watch/$streamId': typeof WatchStreamIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/app-store-assets'
    | '/auth'
    | '/camera'
    | '/check-in'
    | '/community'
    | '/curriculum'
    | '/donate'
    | '/feedback'
    | '/forensics'
    | '/international'
    | '/know-your-rights'
    | '/lawyer-finder'
    | '/legal-tools'
    | '/login'
    | '/map'
    | '/network'
    | '/onboarding'
    | '/org'
    | '/privacy'
    | '/recover-vault'
    | '/safe-corridor'
    | '/settings'
    | '/signup'
    | '/sos'
    | '/transparency'
    | '/vault'
    | '/verify'
    | '/legal/privacy'
    | '/legal/terms'
    | '/watch/$streamId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/app-store-assets'
    | '/auth'
    | '/camera'
    | '/check-in'
    | '/community'
    | '/curriculum'
    | '/donate'
    | '/feedback'
    | '/forensics'
    | '/international'
    | '/know-your-rights'
    | '/lawyer-finder'
    | '/legal-tools'
    | '/login'
    | '/map'
    | '/network'
    | '/onboarding'
    | '/org'
    | '/privacy'
    | '/recover-vault'
    | '/safe-corridor'
    | '/settings'
    | '/signup'
    | '/sos'
    | '/transparency'
    | '/vault'
    | '/verify'
    | '/legal/privacy'
    | '/legal/terms'
    | '/watch/$streamId'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/app-store-assets'
    | '/auth'
    | '/camera'
    | '/check-in'
    | '/community'
    | '/curriculum'
    | '/donate'
    | '/feedback'
    | '/forensics'
    | '/international'
    | '/know-your-rights'
    | '/lawyer-finder'
    | '/legal-tools'
    | '/login'
    | '/map'
    | '/network'
    | '/onboarding'
    | '/org'
    | '/privacy'
    | '/recover-vault'
    | '/safe-corridor'
    | '/settings'
    | '/signup'
    | '/sos'
    | '/transparency'
    | '/vault'
    | '/verify'
    | '/legal/privacy'
    | '/legal/terms'
    | '/watch/$streamId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AppStoreAssetsRoute: typeof AppStoreAssetsRoute
  AuthRoute: typeof AuthRoute
  CameraRoute: typeof CameraRoute
  CheckInRoute: typeof CheckInRoute
  CommunityRoute: typeof CommunityRoute
  CurriculumRoute: typeof CurriculumRoute
  DonateRoute: typeof DonateRoute
  FeedbackRoute: typeof FeedbackRoute
  ForensicsRoute: typeof ForensicsRoute
  InternationalRoute: typeof InternationalRoute
  KnowYourRightsRoute: typeof KnowYourRightsRoute
  LawyerFinderRoute: typeof LawyerFinderRoute
  LegalToolsRoute: typeof LegalToolsRoute
  LoginRoute: typeof LoginRoute
  MapRoute: typeof MapRoute
  NetworkRoute: typeof NetworkRoute
  OnboardingRoute: typeof OnboardingRoute
  OrgRoute: typeof OrgRoute
  PrivacyRoute: typeof PrivacyRoute
  RecoverVaultRoute: typeof RecoverVaultRoute
  SafeCorridorRoute: typeof SafeCorridorRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  SosRoute: typeof SosRoute
  TransparencyRoute: typeof TransparencyRoute
  VaultRoute: typeof VaultRoute
  VerifyRoute: typeof VerifyRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalTermsRoute: typeof LegalTermsRoute
  WatchStreamIdRoute: typeof WatchStreamIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vault': {
      id: '/vault'
      path: '/vault'
      fullPath: '/vault'
      preLoaderRoute: typeof VaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparency': {
      id: '/transparency'
      path: '/transparency'
      fullPath: '/transparency'
      preLoaderRoute: typeof TransparencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sos': {
      id: '/sos'
      path: '/sos'
      fullPath: '/sos'
      preLoaderRoute: typeof SosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-corridor': {
      id: '/safe-corridor'
      path: '/safe-corridor'
      fullPath: '/safe-corridor'
      preLoaderRoute: typeof SafeCorridorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-vault': {
      id: '/recover-vault'
      path: '/recover-vault'
      fullPath: '/recover-vault'
      preLoaderRoute: typeof RecoverVaultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org': {
      id: '/org'
      path: '/org'
      fullPath: '/org'
      preLoaderRoute: typeof OrgRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/network': {
      id: '/network'
      path: '/network'
      fullPath: '/network'
      preLoaderRoute: typeof NetworkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal-tools': {
      id: '/legal-tools'
      path: '/legal-tools'
      fullPath: '/legal-tools'
      preLoaderRoute: typeof LegalToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lawyer-finder': {
      id: '/lawyer-finder'
      path: '/lawyer-finder'
      fullPath: '/lawyer-finder'
      preLoaderRoute: typeof LawyerFinderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/know-your-rights': {
      id: '/know-your-rights'
      path: '/know-your-rights'
      fullPath: '/know-your-rights'
      preLoaderRoute: typeof KnowYourRightsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/international': {
      id: '/international'
      path: '/international'
      fullPath: '/international'
      preLoaderRoute: typeof InternationalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forensics': {
      id: '/forensics'
      path: '/forensics'
      fullPath: '/forensics'
      preLoaderRoute: typeof ForensicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/feedback': {
      id: '/feedback'
      path: '/feedback'
      fullPath: '/feedback'
      preLoaderRoute: typeof FeedbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/donate': {
      id: '/donate'
      path: '/donate'
      fullPath: '/donate'
      preLoaderRoute: typeof DonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curriculum': {
      id: '/curriculum'
      path: '/curriculum'
      fullPath: '/curriculum'
      preLoaderRoute: typeof CurriculumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/community': {
      id: '/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof CommunityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/check-in': {
      id: '/check-in'
      path: '/check-in'
      fullPath: '/check-in'
      preLoaderRoute: typeof CheckInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/camera': {
      id: '/camera'
      path: '/camera'
      fullPath: '/camera'
      preLoaderRoute: typeof CameraRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app-store-assets': {
      id: '/app-store-assets'
      path: '/app-store-assets'
      fullPath: '/app-store-assets'
      preLoaderRoute: typeof AppStoreAssetsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$streamId': {
      id: '/watch/$streamId'
      path: '/watch/$streamId'
      fullPath: '/watch/$streamId'
      preLoaderRoute: typeof WatchStreamIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AppStoreAssetsRoute: AppStoreAssetsRoute,
  AuthRoute: AuthRoute,
  CameraRoute: CameraRoute,
  CheckInRoute: CheckInRoute,
  CommunityRoute: CommunityRoute,
  CurriculumRoute: CurriculumRoute,
  DonateRoute: DonateRoute,
  FeedbackRoute: FeedbackRoute,
  ForensicsRoute: ForensicsRoute,
  InternationalRoute: InternationalRoute,
  KnowYourRightsRoute: KnowYourRightsRoute,
  LawyerFinderRoute: LawyerFinderRoute,
  LegalToolsRoute: LegalToolsRoute,
  LoginRoute: LoginRoute,
  MapRoute: MapRoute,
  NetworkRoute: NetworkRoute,
  OnboardingRoute: OnboardingRoute,
  OrgRoute: OrgRoute,
  PrivacyRoute: PrivacyRoute,
  RecoverVaultRoute: RecoverVaultRoute,
  SafeCorridorRoute: SafeCorridorRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  SosRoute: SosRoute,
  TransparencyRoute: TransparencyRoute,
  VaultRoute: VaultRoute,
  VerifyRoute: VerifyRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalTermsRoute: LegalTermsRoute,
  WatchStreamIdRoute: WatchStreamIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
